spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
